/**************************************************************************/
/*  render_forward_clustered_pso.cpp                                      */
/**************************************************************************/

#include "render_forward_clustered_pso.h"

#include "core/string/print_string.h"
#include "servers/rendering/renderer_rd/pso_record.h"
#include "servers/rendering/renderer_rd/storage_rd/material_storage.h"
#include "servers/rendering/renderer_rd/storage_rd/mesh_storage.h"

using namespace RendererSceneRenderImplementation;

// Hashing the generated source is the only shader identity that survives a restart: shaders
// generated by BaseMaterial3D never receive a path hint, so ShaderData::path is empty for them.
static Mutex shader_hash_mutex;
static HashMap<SceneShaderForwardClustered::ShaderData *, uint64_t> shader_hashes;

static uint64_t _shader_identity(SceneShaderForwardClustered::ShaderData *p_shader) {
	MutexLock lock(shader_hash_mutex);
	const uint64_t *cached = shader_hashes.getptr(p_shader);
	if (cached != nullptr) {
		return *cached;
	}
	const uint64_t hash = p_shader->code.hash64();
	shader_hashes.insert(p_shader, hash);
	return hash;
}

void RenderForwardClusteredPSO::record(SceneShaderForwardClustered::ShaderData *p_shader,
		const SceneShaderForwardClustered::ShaderData::PipelineKey &p_key, uint64_t p_surface_format,
		bool p_instanced, bool p_motion_vectors, bool p_point_size) {
	PSORecord::FBDesc fb;
	if (!PSORecord::framebuffer_desc_for_id(p_key.framebuffer_format_id, fb)) {
		// A format no enumerated descriptor produces cannot be rebuilt, so recording it would
		// promise coverage replay cannot deliver.
		PSORecord::note_unknown_framebuffer(p_key.framebuffer_format_id);
		return;
	}

	PSORecord::Rec rec;
	rec.shader_hash = _shader_identity(p_shader);
	rec.surface_format = p_surface_format;
	rec.fb = fb.pack();
	rec.color_pass_flags = p_key.color_pass_flags;
	rec.spec_0 = p_key.shader_specialization.packed_0;
	rec.spec_1 = p_key.shader_specialization.packed_1;
	rec.spec_2 = p_key.shader_specialization.packed_2;
	rec.cull_mode = uint8_t(p_key.cull_mode);
	rec.primitive = uint8_t(p_key.primitive_type);
	rec.version = uint8_t(p_key.version);
	rec.instanced = p_instanced ? 1 : 0;
	rec.motion_vectors = p_motion_vectors ? 1 : 0;
	rec.point_size = p_point_size ? 1 : 0;
	rec.wireframe = p_key.wireframe ? 1 : 0;
	rec.ubershader = p_key.ubershader ? 1 : 0;
	PSORecord::push(rec);
}

static uint32_t _replay(const LocalVector<PSORecord::Rec> &p_recs, const Vector<RID> &p_materials, uint32_t *r_unmatched) {
	RendererRD::MaterialStorage *material_storage = RendererRD::MaterialStorage::get_singleton();
	RendererRD::MeshStorage *mesh_storage = RendererRD::MeshStorage::get_singleton();

	// Loading a material is what brings its shader into existence; the recorded hash is how a
	// record finds the shader it belongs to.
	HashMap<uint64_t, SceneShaderForwardClustered::ShaderData *> by_hash;
	for (const RID &material : p_materials) {
		RendererRD::MaterialStorage::MaterialData *data = material_storage->material_get_data(material, RendererRD::MaterialStorage::SHADER_TYPE_3D);
		if (data == nullptr) {
			continue;
		}
		SceneShaderForwardClustered::MaterialData *material_data = static_cast<SceneShaderForwardClustered::MaterialData *>(data);
		if (material_data->shader_data == nullptr) {
			continue;
		}
		by_hash[material_data->shader_data->code.hash64()] = material_data->shader_data;
	}

	// Distinct shaders, not records: it is the shader that either exists at replay time or does
	// not, and a single missing one drops every record that belongs to it.
	HashSet<uint64_t> wanted;
	HashSet<uint64_t> missing;
	for (const PSORecord::Rec &rec : p_recs) {
		wanted.insert(rec.shader_hash);
		if (!by_hash.has(rec.shader_hash)) {
			missing.insert(rec.shader_hash);
		}
	}
	String missing_ids;
	for (const uint64_t &hash : missing) {
		missing_ids += vformat(" %d", int64_t(hash));
	}
	print_verbose(vformat("PSO replay: %d materials -> %d shaders live; %d of %d recorded shaders missing:%s",
			p_materials.size(), by_hash.size(), missing.size(), wanted.size(), missing_ids));

	uint32_t submitted = 0;
	uint32_t unmatched = 0;
	for (const PSORecord::Rec &rec : p_recs) {
		SceneShaderForwardClustered::ShaderData **shader = by_hash.getptr(rec.shader_hash);
		if (shader == nullptr) {
			unmatched++;
			continue;
		}

		int64_t framebuffer_format_id = 0;
		if (!PSORecord::framebuffer_id_for_desc(PSORecord::FBDesc::unpack(rec.fb), framebuffer_format_id)) {
			unmatched++;
			continue;
		}

		SceneShaderForwardClustered::ShaderData::PipelineKey key;
		key.version = SceneShaderForwardClustered::PipelineVersion(rec.version);
		key.color_pass_flags = rec.color_pass_flags;
		key.ubershader = rec.ubershader;
		key.wireframe = rec.wireframe;
		key.cull_mode = RD::PolygonCullMode(rec.cull_mode);
		key.primitive_type = RSE::PrimitiveType(rec.primitive);
		key.shader_specialization.packed_0 = rec.spec_0;
		key.shader_specialization.packed_1 = rec.spec_1;
		key.shader_specialization.packed_2 = rec.spec_2;
		key.framebuffer_format_id = framebuffer_format_id;

		// A variant whose group is disabled gets a placeholder with no stages, not a shader, and
		// the driver rejects any pipeline built from it. Enabling the group compiles it now -
		// which is the same work a draw would otherwise force mid-mission.
		const Pair<ShaderRD *, RID> native = (*shader)->get_native_shader_and_version();
		if (native.first == nullptr || native.second.is_null()) {
			unmatched++;
			continue;
		}
		const uint16_t variant = (*shader)->_get_shader_version(key.version, key.color_pass_flags, key.ubershader);
		if (!native.first->is_variant_enabled(variant)) {
			unmatched++;
			continue;
		}
		const int group = native.first->get_variant_to_group(variant);
		if (!native.first->is_group_enabled(group)) {
			native.first->enable_group(group);
		}
		native.first->ensure_version_compiled(native.second);
		if (native.first->version_get_shader(native.second, variant).is_null()) {
			unmatched++;
			continue;
		}

		// The mask depends on the version being built, exactly as the draw path derives it.
		const uint64_t input_mask = (*shader)->get_vertex_input_mask(key.version, key.color_pass_flags, key.ubershader);
		key.vertex_format_id = mesh_storage->mesh_generate_vertex_format(rec.surface_format, input_mask, rec.instanced, rec.motion_vectors, rec.point_size);

		(*shader)->pipeline_hash_map.compile_pipeline(key, key.hash(), RSE::PIPELINE_SOURCE_SURFACE, false);
		submitted++;
	}

	if (r_unmatched != nullptr) {
		*r_unmatched = unmatched;
	}
	return submitted;
}

void RenderForwardClusteredPSO::init() {
	PSORecord::set_replay_function(&_replay);
}
