/**************************************************************************/
/*  render_forward_clustered_pso.cpp                                      */
/**************************************************************************/

#include "render_forward_clustered_pso.h"

#include "render_forward_clustered.h"

#include "core/string/print_string.h"
#include "servers/rendering/renderer_rd/pso_record.h"
#include "servers/rendering/renderer_rd/storage_rd/material_storage.h"
#include "servers/rendering/renderer_rd/storage_rd/mesh_storage.h"

using namespace RendererSceneRenderImplementation;

// Hashing the generated source is the only shader identity that survives a restart: shaders
// generated by BaseMaterial3D never receive a path hint, so ShaderData::path is empty for them.
static _FORCE_INLINE_ uint64_t _shader_identity(SceneShaderForwardClustered::ShaderData *p_shader) {
	return p_shader ? p_shader->code_hash : 0;
}

void RenderForwardClusteredPSO::record(SceneShaderForwardClustered::ShaderData *p_shader,
		const SceneShaderForwardClustered::ShaderData::PipelineKey &p_key, uint64_t p_surface_format,
		bool p_instanced, bool p_motion_vectors, bool p_point_size) {
	PSORecord::FBDesc fb;
	if (!PSORecord::framebuffer_desc_for_id(p_key.framebuffer_format_id, fb)) {
		// A format no enumerated descriptor produces cannot be rebuilt, so recording it would
		// promise coverage replay cannot deliver.
		PSORecord::note_unknown_framebuffer(p_key.framebuffer_format_id);
		return;
	}

	PSORecord::Rec rec;
	rec.shader_hash = _shader_identity(p_shader);
	rec.surface_format = p_surface_format;
	rec.fb = fb.pack();
	rec.color_pass_flags = p_key.color_pass_flags;
	rec.spec_0 = p_key.shader_specialization.packed_0;
	rec.spec_1 = p_key.shader_specialization.packed_1;
	rec.spec_2 = p_key.shader_specialization.packed_2;
	rec.cull_mode = uint8_t(p_key.cull_mode);
	rec.primitive = uint8_t(p_key.primitive_type);
	rec.version = uint8_t(p_key.version);
	rec.instanced = p_instanced ? 1 : 0;
	rec.motion_vectors = p_motion_vectors ? 1 : 0;
	rec.point_size = p_point_size ? 1 : 0;
	rec.wireframe = p_key.wireframe ? 1 : 0;
	rec.ubershader = p_key.ubershader ? 1 : 0;
	PSORecord::push(rec);
}

static void _replay(const LocalVector<PSORecord::Rec> &p_recs, const Vector<RID> &p_materials, uint32_t p_from, uint32_t p_count, bool p_enable_only, PSORecord::ReplayStats &r_stats) {
	RendererRD::MaterialStorage *material_storage = RendererRD::MaterialStorage::get_singleton();
	RendererRD::MeshStorage *mesh_storage = RendererRD::MeshStorage::get_singleton();

	// Loading a material is what brings its shader into existence; the recorded hash is how a
	// record finds the shader it belongs to.
	HashMap<uint64_t, SceneShaderForwardClustered::ShaderData *> by_hash;
	for (const RID &material : p_materials) {
		RendererRD::MaterialStorage::MaterialData *data = material_storage->material_get_data(material, RendererRD::MaterialStorage::SHADER_TYPE_3D);
		if (data == nullptr) {
			continue;
		}
		SceneShaderForwardClustered::MaterialData *material_data = static_cast<SceneShaderForwardClustered::MaterialData *>(data);
		if (material_data->shader_data == nullptr) {
			continue;
		}
		by_hash[material_data->shader_data->code_hash] = material_data->shader_data;
	}

	// Reported once, on the first slice: it describes the whole recording, not this slice.
	if (p_from == 0) {
		HashSet<uint64_t> wanted;
		HashSet<uint64_t> missing;
		for (const PSORecord::Rec &rec : p_recs) {
			wanted.insert(rec.shader_hash);
			if (!by_hash.has(rec.shader_hash)) {
				missing.insert(rec.shader_hash);
			}
		}
		r_stats.shaders_wanted = wanted.size();
		r_stats.shaders_missing = missing.size();
		print_verbose(vformat("PSO replay: %d materials -> %d shaders live; %d of %d recorded shaders missing",
				p_materials.size(), by_hash.size(), missing.size(), wanted.size()));
	}

	// Only the requested slice: enabling a shader group compiles its variants, and doing that for
	// a whole recording in one call is what stalls the main thread on a cold shader cache.
	const uint32_t last = MIN(uint64_t(p_from) + uint64_t(p_count), uint64_t(p_recs.size()));

	uint32_t submitted = 0;
	uint32_t unmatched = 0;
	for (uint32_t i = p_from; i < last; i++) {
		const PSORecord::Rec &rec = p_recs[i];
		SceneShaderForwardClustered::ShaderData **shader = by_hash.getptr(rec.shader_hash);
		if (shader == nullptr) {
			unmatched++;
			continue;
		}

		int64_t framebuffer_format_id = 0;
		if (!PSORecord::framebuffer_id_for_desc(PSORecord::FBDesc::unpack(rec.fb), framebuffer_format_id)) {
			unmatched++;
			continue;
		}

		SceneShaderForwardClustered::ShaderData::PipelineKey key;
		key.version = SceneShaderForwardClustered::PipelineVersion(rec.version);
		key.color_pass_flags = rec.color_pass_flags;
		key.ubershader = rec.ubershader;
		key.wireframe = rec.wireframe;
		key.cull_mode = RD::PolygonCullMode(rec.cull_mode);
		key.primitive_type = RSE::PrimitiveType(rec.primitive);
		key.shader_specialization.packed_0 = rec.spec_0;
		key.shader_specialization.packed_1 = rec.spec_1;
		key.shader_specialization.packed_2 = rec.spec_2;
		key.framebuffer_format_id = framebuffer_format_id;

		// A variant whose group is disabled gets a placeholder with no stages, not a shader, and
		// the driver rejects any pipeline built from it.
		const Pair<ShaderRD *, RID> native = (*shader)->get_native_shader_and_version();
		if (native.first == nullptr || native.second.is_null()) {
			unmatched++;
			continue;
		}
		const uint16_t variant = (*shader)->_get_shader_version(key.version, key.color_pass_flags, key.ubershader);
		if (!native.first->is_variant_enabled(variant)) {
			unmatched++;
			continue;
		}
		// Enabling is non-blocking - it only dispatches the group's variant compiles to the pool.
		// Nothing waits for them here: _create_pipeline runs on a worker and version_get_shader()
		// blocks there, so waiting on this thread would stall the boot screen for the whole
		// compile instead of just queueing the work.
		const int group = native.first->get_variant_to_group(variant);
		if (!native.first->is_group_enabled(group)) {
			native.first->enable_group(group);
		}
		if (p_enable_only) {
			// First pass only starts the compiles. Deriving the vertex format needs the compiled
			// shader's input mask, which would block here until the group finished.
			submitted++;
			continue;
		}

		// The mask depends on the version being built, exactly as the draw path derives it.
		const uint64_t input_mask = (*shader)->get_vertex_input_mask(key.version, key.color_pass_flags, key.ubershader);
		key.vertex_format_id = mesh_storage->mesh_generate_vertex_format(rec.surface_format, input_mask, rec.instanced, rec.motion_vectors, rec.point_size);

		(*shader)->pipeline_hash_map.compile_pipeline(key, key.hash(), RSE::PIPELINE_SOURCE_WARMUP, false);
		submitted++;
	}

	r_stats.submitted = submitted;
	r_stats.unmatched = unmatched;
}

bool RenderForwardClustered::pso_shaders_ready() {
	return !scene_shader.shader.has_pending_group_compiles();
}

void RenderForwardClustered::pso_apply_global_key(uint32_t p_key) {
	// Only the bits that describe the *content*. texture_samples, the two shadow bit depths and
	// multiview are properties of this run's settings and viewport, so a stale recording must
	// never revive them - it would build pipelines for an MSAA level nobody selected.
	GlobalPipelineData content_mask = {};
	content_mask.use_reflection_probes = 1;
	content_mask.use_separate_specular = 1;
	content_mask.use_motion_vectors = 1;
	content_mask.use_normal_and_roughness = 1;
	content_mask.use_lightmaps = 1;
	content_mask.use_voxelgi = 1;
	content_mask.use_sdfgi = 1;
	content_mask.use_shadow_cubemaps = 1;
	content_mask.use_shadow_dual_paraboloid = 1;

	GlobalPipelineData restored = {};
	restored.key = p_key & content_mask.key;

	// A requirement flag is only safe to set once the shader group holding its variants is
	// enabled: a disabled group hands out placeholder RIDs with no stages, and the driver rejects
	// any pipeline built from one ("Pre-raster shader is not provided"). Upstream never hits this
	// because a flag becomes true at the moment the feature is first used, which is also when the
	// group is enabled - restoring the flag ahead of time has to enable the group itself.
	if (restored.use_separate_specular || restored.use_motion_vectors || restored.use_lightmaps ||
			restored.use_voxelgi || restored.use_sdfgi) {
		scene_shader.enable_advanced_shader_group(global_pipeline_data_required.use_multiview);
	}

	// OR, never assign: whatever this run has already discovered stays required.
	global_pipeline_data_required.key |= restored.key;
}

static uint64_t _material_shader_hash(RID p_material) {
	RendererRD::MaterialStorage::MaterialData *data = RendererRD::MaterialStorage::get_singleton()->material_get_data(p_material, RendererRD::MaterialStorage::SHADER_TYPE_3D);
	if (data == nullptr) {
		return 0;
	}
	SceneShaderForwardClustered::MaterialData *material_data = static_cast<SceneShaderForwardClustered::MaterialData *>(data);
	if (material_data->shader_data == nullptr) {
		return 0;
	}
	return material_data->shader_data->code_hash;
}

static bool _shaders_ready() {
	RenderForwardClustered *renderer = RenderForwardClustered::get_singleton();
	return renderer == nullptr || renderer->pso_shaders_ready();
}

static void _apply_global_key(uint32_t p_key) {
	RenderForwardClustered *renderer = RenderForwardClustered::get_singleton();
	if (renderer != nullptr) {
		renderer->pso_apply_global_key(p_key);
	}
}

void RenderForwardClusteredPSO::init() {
	PSORecord::set_replay_function(&_replay);
	PSORecord::set_ready_function(&_shaders_ready);
	PSORecord::set_shader_hash_function(&_material_shader_hash);
	PSORecord::set_apply_global_key_function(&_apply_global_key);
}
